### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by 18822591236** [CVer-Yang/RCFSNet#3]
1.13.1+cu117
RCFSNetMas
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/RCFSNet-main/main_RCFSNet_Mas.py", line 121, in <module>
    CE_Net_Train()
  File "C:/Users/lenovo/Desktop/RCFSNet-main/main_RCFSNet_Mas.py", line 44, in CE_Net_Train
    solver = MyFrame(RCFSNet, dice_bce_loss, 2e-4)
  File "C:\Users\lenovo\Desktop\RCFSNet-main\framework.py", line 11, in __init__
    self.net = net().cuda()
  File "D:\Anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "D:\Anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\Anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "D:\Anaconda3\envs\deep_learning\lib\site-packages\torch\cuda\__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by CVer-Yang** [comment]
you can see your the version is pytorch-gpu,and the my device is set 0,1,2,3
